site_name: TatSu
site_url: https://tatsu.readthedocs.io/
repo_url: https://github.com/neogeny/TatSu
edit_uri: edit/master/docs/

# Relative to this config file (inside /mkdocs/)
docs_dir: docs

theme:
  name: material
  font:
    text: Calibri
    code: JetBrains Mono
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: grey
      accent: grey
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: grey
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - content.code.copy
    - navigation.expand  # Expand navigation sections automatically
    - navigation.instant  # Instant navigation without page reloads
    - navigation.instant.preview # Preload pages on hover for faster navigation
    - navigation.sections
    - navigation.top
    - navigation.tracking
    - search.suggest
    - search.highlight
    - toc.follow      # Highlight the current section while scrolling
    - toc.integrate   # (Optional) Merge TOC into the left sidebar for a cleaner look
    - navigation.top  # Adds a "Back to top" button

markdown_extensions:
  - admonition
  - attr_list
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
  - tables
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:pymdownx.emoji.gemoji
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - toc:
      baselevel: 1
      toc_depth: 3

      permalink: "â‡™"
      permalink_title: Link  # Hover text for the permalink
#      permalink_class: link  # CSS class for the permalink <a> tag

      # --- ID & Slug Logic ---
#      separator: "-"         # Character used to replace spaces in IDs
#      slugify: !!python/name:pymdownx.slugs.slugify # Logic for creating IDs
#      anchor_linenums: false # If using line numbers, should they have anchors?

      # --- Behavior ---
      marker: "[TOC]"        # The string to look for to insert a TOC in-page

plugins:
  - search
  - macros
  - mkdocstrings:
      handlers:
        python:
          paths: [".."]
          options:
            show_source: true
            show_root_heading: true
            show_category_heading: true
            docstring_style: sphinx
extra:
  dragon: "&#x7ADC;"
  TatSu: "&#x7ADC; **TatSu**"
  end: '</span>'
  red: '<span style="color:red">'
  green: '<span style="color:green">'
  blue: '<span style="color:blue">'
  yellow: '<span style="color:yellow">'
  none: '<span style="color:none">'
  console: '<span style="color:none">'
  try: '<span style="color:yellow">'
  succeed: '<span style="color:green">'
  fail: '<span style="color:red">'

nav:
  - Home: index.md
  - Introduction: intro.md
  - Rationale: rationale.md
  - Installation: install.md
  - Using the Tool: use.md
  - Parser Configuration: parserconfig.md
  - Grammar Syntax: syntax.md
  - Grammar Directives: directives.md
  - Abstract Syntax Trees: ast.md
  - Semantic Actions: semantics.md
  - Models: models.md
  - Translation: translation.md
  - Left Recursion: left_recursion.md
  - Mini Tutorial: mini-tutorial.md
  - Traces: traces.md
  - Importing from ANTLR: antlr.md
  - Examples: examples.md
  - Support: support.md
  - Credits: credits.md
  - Contributors: contributors.md
  - Contributing: contributing.md
  - Lincense: license.md
  - References: links.md

#nav:
#  - Home: index.md
#  - Introduction: intro.md
#  - Rationale: rationale.md
#  - Installation: install.md
#  - Using the Tool: use.md
#  - Parser Configuration: parserconfig.md
#  - Grammar Syntax: syntax.md
#  - Grammar Directives: directives.md
#  - "Abstract Syntax Trees (ASTs)": ast.md
#  - Semantic Actions: semantics.md
#  - Models:
#      - Overview: models.md
#      - Building Models: ""#building-models"
#      - Viewing as JSON: "#viewing-models-as-json"
#      - Walking Models: "#walking-models"
#  - Translation: translation.md
#  - Left Recursion: left_recursion.md
#  - Mini Tutorial: mini-tutorial.md
#  - Traces: traces.md
#  - ANTLR Grammars: antlr.md
#  - Examples: examples.md
#  - Support: support.md
#  - Credits: credits.md
#  - License: license.md
#  - Project Info:
#      - Contributing: contributing.md
#      - Contributors: contributors.md
#      - Links: links.md

